name: device_info
description: Get information from the user's device
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mocktail: ^0.3.0

flutter:
