# we use the lint package for lint rules https://pub.dev/packages/lint
include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    avoid_catching_errors: false
