name: fpaper

packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  test-all:
    run: flutter test test && flutter test packages/auth/test && flutter test packages/core/test && flutter test packages/device_info/test && flutter test packages/auth/test;
    description: Run test in all packages.
