name: fpaper
description: An app to set wallpaper to your friends device

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  auth:
    path: packages/auth
  core:
    path: packages/core
  db:
    path: packages/db
  device_info:
    path: packages/device_info
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.0.0-dev.5
  github_sign_in: ^0.0.5-dev.4
  go_router: ^4.2.7
  google_sign_in: ^5.3.1
  rxdart: ^0.27.5

  ui:
    path: packages/ui
  wallpaper:
    path: packages/wallpaper

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
